### ISSUE TITLE
Error Consulta RUC

### ISSUE THREAD

**Issue by CarlosX** [JossMP/SunatPHP#11]
Desde el 2019-08-06 no esta funcionando

**Comment by tavosud** [comment]
Me pasa lo mismo :(

**Comment by Kevincanvas** [comment]
Si desde la misma fecha 2019-08-06 me ha dejado de funcionar, Mi ultima consulta fue 2019-08-05 18:54:24

**Comment by Kevincanvas** [comment]
![image](https://user-images.githubusercontent.com/4044239/62578106-ef72da00-b865-11e9-8096-ad13ce469753.png)

Cuando se utiliza http://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias

**Comment by ghost** [comment]
¿Alguna solución?

**Comment by riux** [comment]
Tengo el mismo problema

**Comment by tavosud** [comment]
Ha vuelto a funcionar el código... esos ineptos de la sunat deberían facilitarnos funciones y no complicarnos la vida.

**Comment by CarlosX** [comment]
La Sunat tiene algún servicio de pago ?

**Comment by Kevincanvas** [comment]
Ha vuelto a funcionar el código
