### ISSUE TITLE
Falla el servicio, El metodo getNumRand() al ingresar a la url se muestra un error.

### ISSUE THREAD

**Issue by BryanCardiet** [JossMP/SunatPHP#17]
Al ingresar a la url  "https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/captcha?accion=random" de manera "manual" obtengo el error.

`
The requested URL was rejected. Please consult with your administrator.

Your support ID is: xxxxxxxxxxxxxx

[Go Back]
`
Si alguien a logrado solucionar este detalle, se lo agradecería. Gracias

**Comment by washingtonaya** [comment]
Estimado lograste solucionar?

**Comment by BryanCardiet** [comment]
aún no consigo solución, comenzaron a usar recatchap 3 y luego de una cantidad de intentos fallidos, el servidor me bloquea la entrada

**Comment by washingtonaya** [comment]
Vi en otro lado que están utilizando como solución alternativa, para obtener el valor numRnd de esta pagina https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=

pero no se como implementarlo, haber si puedes implementarlo.

**Comment by BryanCardiet** [comment]
si esta interesante, pero parece que no funciona para consultas  con ruc, solo con razón social. voy a intentar y aviso por aca si consigo obtener los datos

**Comment by BryanCardiet** [comment]
igual de manera de respaldo yo uso este api: https://api.apis.net.pe/v1/ruc?numero=xxxxxxxxxxx
da una cantidad de datos reducida pero para emergencias funciona.

**Comment by vitmaraliaga** [comment]
Hola, alguien logró solucionar este problema?

**Comment by washingtonaya** [comment]
> si esta interesante, pero parece que no funciona para consultas con ruc, solo con razón social. voy a intentar y aviso por aca si consigo obtener los datos

Es para obtener el numRnd en HTML 
![image](https://user-images.githubusercontent.com/77364874/118309612-1cc8cf00-b4b3-11eb-9ed5-7aff599b09ce.png)

**Comment by washingtonaya** [comment]
> igual de manera de respaldo yo uso este api: https://api.apis.net.pe/v1/ruc?numero=xxxxxxxxxxx
> da una cantidad de datos reducida pero para emergencias funciona.

Gracias, lo tomare como fuente opcional ya lo implemente, hasta tener una solución y si  logro algo compartiré

**Comment by baldarrago** [comment]
Logré obtener el numRand:

![code](https://user-images.githubusercontent.com/30669808/118314577-f22e4480-b4b9-11eb-9b7f-eb1dec2b0d6e.png)

**Comment by Kevincanvas** [comment]
> Logré obtener el numRand:
> 
> ![code](https://user-images.githubusercontent.com/30669808/118314577-f22e4480-b4b9-11eb-9b7f-eb1dec2b0d6e.png)

Gracias. Logro traer la data aunque me parece que demora un tanto mas en cargar

**Comment by washingtonaya** [comment]
> Logré obtener el numRand:
> 
> ![code](https://user-images.githubusercontent.com/30669808/118314577-f22e4480-b4b9-11eb-9b7f-eb1dec2b0d6e.png)

Estimado que versión de php estas usando ya que a mi me bota un error, mi versión de php es 7.3
`<br />
<b>Warning</b>:  Use of undefined constant REG_SET_ORDER - assumed 'REG_SET_ORDER' (this will throw an Error in a future version of PHP) in <b>C:\laragon\www\sunat\src\sunat\sunat.php</b> on line <b>54</b><br />
<br />
<b>Warning</b>:  preg_match_all() expects parameter 4 to be int, string given in <b>C:\laragon\www\sunat\src\sunat\sunat.php</b> on line <b>54</b><br />
{
    "success": false,
    "message": "No se encontraron datos suficientes."
}`

**Comment by washingtonaya** [comment]
Ahora el servicio para obtener el random, esta cerrado 
para seguir obteniendo el random hay que agregarle un razón social, con eso  estaríamos teniendo una solución temporal . 

Saludos !!

**Comment by FranciscoOrrego** [comment]
> Ahora el servicio para obtener el random, esta cerrado
> para seguir obteniendo el random hay que agregarle un razón social, con eso estaríamos teniendo una solución temporal .
> 
> Saludos !!


Como agregarle una razon social? podrias  apoyarnos en explicar.. se le coloca  en la ruta  $url??

**Comment by washingtonaya** [comment]
> > Ahora el servicio para obtener el random, esta cerrado
> > para seguir obteniendo el random hay que agregarle un razón social, con eso estaríamos teniendo una solución temporal .
> > Saludos !!
> 
> Como agregarle una razon social? podrias apoyarnos en explicar.. se le coloca en la ruta $url??

`$url="https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=MTS";`

**Comment by FranciscoOrrego** [comment]
> > > Ahora el servicio para obtener el random, esta cerrado
> > > para seguir obteniendo el random hay que agregarle un razón social, con eso estaríamos teniendo una solución temporal .
> > > Saludos !!
> > 
> > 
> > Como agregarle una razon social? podrias apoyarnos en explicar.. se le coloca en la ruta $url??
> 
> `$url="https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=MTS";`

Muchas gracias compañero

**Comment by BryanCardiet** [comment]
han cerrado el portal de consulta sunat por ruc, ahora se activo un nuevo portal para descargar la información.

**Comment by washingtonaya** [comment]
> han cerrado el portal de consulta sunat por ruc, ahora se activo un nuevo portal para descargar la información.

Saludos estimado, podría colocar el link del nuevo portal.
