### ISSUE TITLE
Consulta ruc. no se encuentra el url de ramdom

### ISSUE THREAD

**Issue by washingtonaya** [JossMP/SunatPHP#19]
El url para la búsqueda de datos por razón social ya no funciona
https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=MTS

En otro lado vi como alternativa lo están haciendo por la consulta masiva usando 2 link, pero en este caso se obtendría en zip y luego leer los datos en que esta en txt.
1-llamar al numero random https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/captcha?accion=random
2/https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/jrmS00Alias?accion=consManual&txtRuc&selRuc=20574694044&random=-467862007

Haber si alguien podría apoyar con la implementación.

**Comment by Jcoding24** [comment]
> El url para la búsqueda de datos por razón social ya no funciona
> https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=MTS
> 
> En otro lado vi como alternativa lo están haciendo por la consulta masiva usando 2 link, pero en este caso se obtendría en zip y luego leer los datos en que esta en txt.
> 1-llamar al numero random https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/captcha?accion=random
> 2/https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/jrmS00Alias?accion=consManual&txtRuc&selRuc=20574694044&random=-467862007
> 
> Haber si alguien podría apoyar con la implementación.

Lograron implementar esto? me quede en la version donde poniamos el link que culimaba en MTS o se ha encontrado la solucion cambiado por otro link?

**Comment by washingtonaya** [comment]
El repositorio esta actualizado por el autor, solo queda que actualices a la ultima versión y esta  funcionando  ok
