### ISSUE TITLE
Problemas con el autocargador de Composer

### ISSUE THREAD

**Issue by ghost** [JossMP/SunatPHP#4]
Resulta que cuando quiero usar la clase \Sunat\Sunat en un servidor linux, me muestra lo siguiente "Class not found" y es debido a que el servidor es insensible a mayúsculas y minúsculas, cómo puedo solucionar ese problema, gracias

**Comment by nashvent** [comment]
Subi un fork de este repositorio con la corrección del autoload en composer
`composer require nashvent/sunatphp`
